apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy
  project: default
  source:
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.7.0
    chart: trivy-operator
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true