apiVersion: batch/v1
kind: Job
metadata:
  name: apply-argo-apps
spec:
  template:
    spec:
      containers:
      - name: kubectl
        image: kubectl
        command: ["kubectl", "apply", "-f", "/path/to/app1.yaml", "-f", "/path/to/app2.yaml"]
      restartPolicy: Never
  backoffLimit: 4